name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  html:
    name: Build HTML
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build HTML
        run: ./gradlew html:dist
      - uses: actions/upload-artifact@v1
        with:
          name: HTML
          path: html/build/dist

      - name: Upload with FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: 'ftp.brommund.se'
          user: 'brommund.se'
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'html/build/dist'
          remoteDir: '.'
          forceSsl: 'false'

  desktop:
    name: Build Desktop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Desktop
        run: ./gradlew desktop:dist
      - uses: actions/upload-artifact@v1
        with:
          name: Desktop
          path: desktop/build/libs
